### ISSUE TITLE
Smart dependency management

### ISSUE THREAD

**Issue by Ceasar** [Ceasar/staticjinja#20]
When a partial is modified, _all_ templates, including those that do no not rely on it, are rebuilt.

This is of course inefficient and rather brutal, but is sufficient for small static sites. For larger site, users may want something more efficient.

Some discussion has already occurred in https://github.com/Ceasar/staticjinja/pull/17.

**Comment by NickCrews** [comment]
It looks like there hasn't been any action on this in ages, and the referenced PRs don't merge cleanly at this point. If someone wants to reopen it feel free.
