### ISSUE TITLE
Inconsistent path separators

### ISSUE THREAD

**Issue by thachhoang** [Ceasar/staticjinja#38]
Jinja2's [FileSystemLoader](https://github.com/mitsuhiko/jinja2/blob/85820fceb83569df62fa5e6b9b0f2f76b7c6a3cf/jinja2/loaders.py#L189) converts all separators to Unix-style while Renderer uses `os.path.sep` (for static file detection, etc.), which breaks on Windows.

Changed file paths returned by easywatch are also OS-dependent.

Should staticjinja try to normalize all file paths coming its way?

**Comment by Ceasar** [comment]
Just seeing this for the first time now. My mistake.

Yeah, I think this change would definitely be a good thing. Have you made a fix yourself already? If not I'll look into this this weekend and make the change.

**Comment by thachhoang** [comment]
I got sidetracked by other things, I don't think I'll have a fix ready. :(

**Comment by toolness** [comment]
Just wanted to mention that I think at least part of this was fixed by 08302aa34fea2df05581b2970e23f8a033b523f3. However, that commit was made on Jan 24, three days after the most recent release (as of today, November 20) to PyPi, which means the fix isn't yet live on PyPi.

**Comment by NickCrews** [comment]
> Just wanted to mention that I think at least part of this was fixed by [08302aa](https://github.com/Ceasar/staticjinja/commit/08302aa34fea2df05581b2970e23f8a033b523f3). However, that commit was made on Jan 24, three days after the most recent release (as of today, November 20) to PyPi, which means the fix isn't yet live on PyPi.

Version 0.3.5 is on PyPi with that fix, so I think we're good. Also I just added test coverage for Windows on Travis in https://github.com/Ceasar/staticjinja/pull/86/commits/d50f5e8a99e9325d7f04422f5cfa57b474fb500c, so hopefully that will catch separator bugs in the future.

**Comment by PatrickMassot** [comment]
Since staticjinja seems maintained again, let me mention I think the future proof fix in this issue would be to switch to using [pathlib](https://docs.python.org/3.5/library/pathlib.html) everywhere.
