### ISSUE TITLE
How to add jinja2 filters?

### ISSUE THREAD

**Issue by sahuguet** [Ceasar/staticjinja#40]
I would like to be able to define my own jinja2 filters.
The current code instantiate the environment (at https://github.com/Ceasar/staticjinja/blob/master/staticjinja/staticjinja.py#L353) and there is no way to pass any filter.
Once the Renderer is created, there is no way to access the environment underneath.

To support filters, I see two options:
- change the make_renderer method to add a new parameter called filters=[]
- add a method to class Renderer (https://github.com/Ceasar/staticjinja/blob/master/staticjinja/staticjinja.py#L22) with a method to get the underlying environment object.

**Comment by Ceasar** [comment]
I like the first option better, adding filters, since I would prefer to hide details of the Environment object (ideally, all of Jinja's API from the end-user). Do you want to add it and submit a PR?

**Comment by sahuguet** [comment]
Ok, I will work on it later today.

**Comment by sahuguet** [comment]
I submitted a PR yesterday.
