### ISSUE TITLE
searchpath argument relative to /usr/local/bin

### ISSUE THREAD

**Issue by justmytwospence** [Ceasar/staticjinja#53]
Whatever I use as the searchpath argument to make_site, its treated as relative to `usr/local/bin` for some reason.

**Comment by Ceasar** [comment]
Hm, can you elaborate? How do you know it's `usr/local/bin`?

**Comment by Ceasar** [comment]
I'm going to close this, because this is not an issue with the project as much as support. But feel free to discuss the issue here further. I haven't figured out a good place to offer support yet.

**Comment by justmytwospence** [comment]
Thanks. For example:

```
site = make_site(searchpath='templates', outpath='public')
print(site)
```

prints:

```
Site('/usr/local/bin/templates', 'public')
```

I've tried making sure that the python directory is set to the script's directory, ie:

```
abspath = os.path.abspath(__file__)
os.chdir(os.path.dirname(abspath))
```

**Comment by Ceasar** [comment]
Weird, I'm not getting on a fresh install into a virtual environment. Can you try that and tell me what happens?
