### ISSUE TITLE
overriding Site in make_site()

### ISSUE THREAD

**Issue by nyov** [Ceasar/staticjinja#68]
The docs have a line saying `To change which files are considered templates, subclass the Site object and override is_template.`

Would it be possible to add a `site_cls` parameter to `make_site()` for using a custom `Site()` class, then?
Without a monkey-patch like the following, it doesn't seem possible right now:

``` py
import staticjinja
from staticjinja import Site, make_site

class MySite(Site):
    def is_template(self, filename):
        return False

staticjinja.staticjinja.Site = MySite
# ...
```

Or am I missing something?

**Comment by PatrickMassot** [comment]
I don't think you are missing anything. You also need to redefine ``make_site`` to use ``MySite``. 

Alternatively you can play with PR #65 (see https://github.com/PatrickMassot/staticjinja/tree/smart_reload_reloaded). This a huge refactor and, among other things, it allows much easier subclassing. For instance ``make_site`` is a class method so you could use ``MySite.make_site``.

**Comment by nyov** [comment]
Thanks for the check and for the link.
I don't actually want to dive that deeply into the project to understand it enough to make sense of your big rewrite on top of it (Sorry).

So I'll just keep my monkeypatch at this time, works okay enough.
And thanks for working on this project!

**Comment by Ceasar** [comment]
You're not missing anything.

I think the correct fix here is to make `make_site` a static or class method, that way if we subclass `Site`, we can still use `make_site` to build an object.

**Comment by Ceasar** [comment]
I made a fix to the code here: https://github.com/Ceasar/staticjinja/commit/b13ddaebe4c4d42063baa257e2f897e1231c1a90

It'll be available in the next version. Thanks for reporting!
