### ISSUE TITLE
env_globals is unexpected kwarg for make_site()

### ISSUE THREAD

**Issue by davidrpmorris** [Ceasar/staticjinja#76]
Even when using the example from the docs:

    if __name__ == "__main__":
        site = staticjinja.make_site(env_globals={
            'greeting':'Hello world!',
        })
        site.render()

I get:

    TypeError: make_site() got an unexpected keyword argument 'env_globals'

**Comment by PatrickMassot** [comment]
My guess is: you are using the latest release on pypi (what you get from ``pip install staticjinja``) but reading bleeding edge documentation. The feature you want to use was added after the most recent release. Before you ask: I'm not the maintainer of this great package so I cannot help you more.

**Comment by Ceasar** [comment]
I'm sorry about that, have been a little neglectful and haven't solved the issue of versioning the docs. If this bites you again, I suggest checking out the source code- it's only around 100 lines or so minus all the comments.

**Comment by davidrpmorris** [comment]
No worries! I was hasty in opening the issue. I just figured that `env_globals` was such a useful feature that it would've been committed long ago. Great project!
