### ISSUE TITLE
Please tag versions on git

### ISSUE THREAD

**Issue by Fale** [Ceasar/staticjinja#77]
Can you please add the versions in git as tags? This really helps out to see quickly changes and all from version to version

**Comment by Ceasar** [comment]
Hi Fale, yeah I can do that. Honestly haven't used them before, but I've been meaning to learn them anyway. :) I'll see if I can do by tomorrow evening.

In the meantime, I have a changelog that records everything in text: https://github.com/Ceasar/staticjinja/blob/master/CHANGELOG.rst

**Comment by Fale** [comment]
to tag a commit you need to do the following:

```
# checkout the commit that you want to tag
git checkout COMMIT-ID
# create the tag
git tag TAG-NAME
# push the tag to github
git push origin TAG-NAME
```

**Comment by Ceasar** [comment]
Thanks for that info. I tagged the latest four versions.
